DROP TRIGGER IF EXISTS update_tot_cred;
DROP PROCEDURE IF EXISTS register_student;
DROP TABLE IF EXISTS takes;
DROP TABLE IF EXISTS section;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS instructor;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS department;
CREATE TABLE department (dept_name VARCHAR(20), building VARCHAR(15), budget NUMERIC(12,2), PRIMARY KEY (dept_name));
CREATE TABLE instructor (ID VARCHAR(5), name VARCHAR(20), dept_name VARCHAR(20), salary NUMERIC(8,2), PRIMARY KEY (ID), FOREIGN KEY (dept_name) REFERENCES department(dept_name));
CREATE TABLE student (ID VARCHAR(5), name VARCHAR(20), dept_name VARCHAR(20), tot_cred NUMERIC(3,0) DEFAULT 0, PRIMARY KEY (ID), FOREIGN KEY (dept_name) REFERENCES department(dept_name));
CREATE TABLE course (course_id VARCHAR(8), title VARCHAR(50), dept_name VARCHAR(20), credits NUMERIC(2,0), PRIMARY KEY (course_id), FOREIGN KEY (dept_name) REFERENCES department(dept_name));
CREATE TABLE section (course_id VARCHAR(8), sec_id VARCHAR(8), semester VARCHAR(6), year NUMERIC(4,0), PRIMARY KEY (course_id, sec_id, semester, year), FOREIGN KEY (course_id) REFERENCES course(course_id));
CREATE TABLE takes (ID VARCHAR(5), course_id VARCHAR(8), sec_id VARCHAR(8), semester VARCHAR(6), year NUMERIC(4,0), grade VARCHAR(2), PRIMARY KEY (ID, course_id, sec_id, semester, year), FOREIGN KEY (ID) REFERENCES student(ID), FOREIGN KEY (course_id, sec_id, semester, year) REFERENCES section(course_id, sec_id, semester, year));
INSERT INTO department VALUES ('Comp. Sci.', 'Taylor', 100000);
INSERT INTO department VALUES ('Biology', 'Watson', 90000);
INSERT INTO instructor VALUES ('10101', 'Srinivasan', 'Comp. Sci.', 65000);
INSERT INTO instructor VALUES ('22222', 'Einstein', 'Biology', 95000);
INSERT INTO course VALUES ('CS-101', 'Intro to CS', 'Comp. Sci.', 4);
INSERT INTO course VALUES ('CS-315', 'Robotics', 'Comp. Sci.', 3);
INSERT INTO course VALUES ('BIO-101', 'Intro to Bio', 'Biology', 3);
INSERT INTO section VALUES ('CS-101', '1', 'Fall', 2024);
INSERT INTO section VALUES ('CS-315', '1', 'Spring', 2025);
INSERT INTO student VALUES ('00128', 'Zhang', 'Comp. Sci.', 0);
INSERT INTO student VALUES ('12345', 'Shankar', 'Comp. Sci.', 0);
